# Generated by Django 5.0.1 on 2024-01-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='country',
        ),
        migrations.DeleteModel(
            name='region',
        ),
        migrations.RemoveField(
            model_name='city',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='city',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='city',
            name='region_id',
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
